name              'passenger_apache2_test'
maintainer        'Chef Software, Inc..'
maintainer_email  'cookbooks@chef.io'
license           'Apache 2.0'
description       'This cookbook is used with test-kitchen to test the parent, passenger_apache2 cookbok'
version           '1.0.0'
