driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.7
  - name: centos-7.2
  - name: debian-7.9
    run_list: apt::default
  - name: debian-8.2
    run_list: apt::default
  - name: freebsd-9.3
    run_list: freebsd::portsnap
  - name: freebsd-10.2
    run_list: freebsd::portsnap
  - name: fedora-22
    run_list: yum::dnf_yum_compat
  - name: fedora-23
    run_list: yum::dnf_yum_compat
  - name: ubuntu-12.04
    run_list: apt::default
  - name: ubuntu-14.04
    run_list: apt::default

suites:
- name: default
  run_list:
  - recipe[passenger_apache2]
  attributes: {}

- name: package
  run_list:
  - recipe[passenger_apache2_test::package]
  - recipe[passenger_apache2]
  excludes: ["centos-6.7", "centos-7.1", "fedora-22"]
  attributes: {}

- name: version-override
  run_list:
  - recipe[passenger_apache2]
  excludes: ["centos-6.7", "centos-7.1", "ubuntu-12.04", "fedora-22"]
  attributes:
    passenger:
      version: "4.0.5"
      module_path: "/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/passenger-4.0.5/libout/apache2/mod_passenger.so"
