driver:
  name: vagrant

provisioner:
  name: chef_zero
  deprecations_as_errors: true

platforms:
  - name: centos-6.8
  - name: centos-7.3
  - name: debian-7.11
    run_list: apt::default
  - name: debian-8.6
    run_list: apt::default
  - name: freebsd-10.3
    run_list: freebsd::portsnap
  - name: freebsd-11.0
    run_list: freebsd::portsnap
  - name: fedora-25
  - name: ubuntu-14.04
    run_list: apt::default
  - name: ubuntu-16.04
    run_list: apt::default

suites:
- name: source
  run_list:
  - recipe[passenger_apache2]

- name: package
  run_list:
  - recipe[passenger_apache2_test::package]
  - recipe[passenger_apache2]
  excludes: ["centos-6.8", "centos-7.3", "fedora-25"]

- name: version-override
  run_list:
  - recipe[passenger_apache2]
  excludes: ["centos-6.8", "centos-7.3", "fedora-25"]
  attributes:
    passenger:
      version: "4.0.5"
      module_path: "/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/passenger-4.0.5/libout/apache2/mod_passenger.so"
