name              "passenger_apache2"
maintainer        "Opscode, Inc."
maintainer_email  "cookbooks@opscode.com"
license           "Apache 2.0"
description       "This cookbook is used with test-kitchen to test the parent, passenger_apache2 cookbok"
version           "1.0.0"
